services:
  ldap:
    image: bitnamilegacy/openldap:latest
    ports:
      - "1389:1389"
    environment:
      - LDAP_ROOT=dc=order,dc=services
    volumes:
      - type: bind
        source: ./infrastructure/ldap/ldifs
        target: /ldifs

  keycloak:
    image: docker.io/bitnamilegacy/keycloak:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgresql
    ports:
      - "80:8080"
        
  postgresql:
    image: docker.io/bitnamilegacy/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
      
  keycloak-setup:
    image: docker.io/bitnamilegacy/keycloak:latest
    build:
      context: .
      args:
        KEYCLOAK_IMAGE_URL: docker.io/bitnamilegacy/keycloak:latest
      dockerfile: kc-setup-Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy
    restart: on-failure
    command: >
      sh -c "/opt/bitnami/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080 --realm master --user user --password bitnami --config /tmp/kcadm.config &&
            /opt/bitnami/keycloak/bin/kcadm.sh get realms/master --server http://keycloak:8080 --realm master --fields id --config /tmp/kcadm.config | jq .id > /tmp/master.realm.id &&
            /opt/bitnami/keycloak/bin/kcadm.sh create components --realm master -s parentId=$(cat /tmp/master.realm.id) --file provisioning/user-federation/storage-provider-config.json --config /tmp/kcadm.config"

    volumes:
      - ./infrastructure/keycloak:/provisioning
